---
- name: Update Home Servers
  hosts: update_list
  tasks:
    - name: apt-get update && apt-get upgrade
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        upgrade: yes

